<template>
  <section class="page">
    <div class="page-header"><div><h1 class="page-title">Mootdx 日线质量</h1><p class="page-subtitle">核验缺口、回补真实成交日线，并保留来源证据。</p></div><div class="toolbar"><el-select v-model="lookbackDays" style="width:116px" @change="load"><el-option :value="10" label="近 10 日" /><el-option :value="30" label="近 30 日" /><el-option :value="60" label="近 60 日" /></el-select><el-button @click="router.push({ name: 'mootdx-monitor' })">返回数据源</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div>
    <section v-if="activeJob" class="job-panel"><div><strong>{{ jobLabel(activeJob.kind) }}</strong><span>{{ activeJob.progress.message }}</span></div><div class="job-progress"><el-progress :percentage="activeJob.progress.percent" :status="activeJob.status === 'failed' ? 'exception' : activeJob.status === 'success' ? 'success' : undefined" /><small>{{ activeJob.progress.processed ?? 0 }} / {{ activeJob.progress.total ?? '-' }}，{{ mootdxStatusText(activeJob.status) }}</small></div><el-button link @click="pollJob">刷新进度</el-button></section>
    <section class="panel"><div class="section-header"><div><h2>按交易日核查缺口</h2><p>先选择交易日，再处理该日的真实缺口；停牌占位记录不会写入日线表。</p></div><div class="date-query"><span>查询交易日</span><el-select v-model="selectedTradeDate" placeholder="选择交易日" style="width:150px" @change="selectedItems = []"><el-option v-for="coverage in dailyCoverageOptions" :key="coverage.trade_date" :label="coverage.trade_date" :value="coverage.trade_date" /></el-select></div></div><div class="coverage-strip" aria-label="交易日覆盖"><button v-for="coverage in dailyCoverageOptions" :key="coverage.trade_date" class="coverage-day" :class="{ active: coverage.trade_date === selectedTradeDate, complete: coverage.missing_symbols === 0 }" type="button" @click="selectTradeDate(coverage.trade_date)"><span>{{ coverage.trade_date.slice(5) }}{{ coverage.trade_date === snapshot?.summary.latest_trade_date ? ' 最新' : '' }}</span><strong>缺失 {{ formatNumber(coverage.missing_symbols) }}</strong><small>{{ percentage(coverage.completeness_rate) }}</small></button></div><div class="selected-day-summary"><div class="selected-day-heading"><strong>{{ selectedTradeDate || '未选择交易日' }}</strong><span>该日覆盖、缺口分类与可处理数量</span></div><div class="selected-day-metrics"><div><span>目录预期</span><strong>{{ formatNumber(selectedCoverage?.expected_symbols) }}</strong></div><div><span>实际日线</span><strong>{{ formatNumber(selectedCoverage?.actual_symbols) }}</strong></div><div><span>物理缺失</span><strong>{{ formatNumber(selectedCoverage?.missing_symbols) }}</strong></div><div><span>已知无数据</span><strong>{{ formatNumber(resolvedNoDataCount) }}</strong></div><div><span>待处理缺口</span><strong>{{ formatNumber(actionableGapCount) }}</strong></div><div><span>有效覆盖</span><strong>{{ percentage(effectiveCoverageRate) }}</strong></div></div></div><div class="section-header queue-toolbar"><div><strong>{{ selectedTradeDate || '未选择交易日' }} 缺失明细</strong><small>建议回补 {{ formatNumber(gapCount('repair_candidate')) }}，待核验 {{ formatNumber(gapCount('needs_review')) }}</small></div><div class="gap-actions"><el-radio-group v-model="gapFilter" size="small"><el-radio-button label="all">全部 {{ formatNumber(dateGapDetails.length) }}</el-radio-button><el-radio-button label="repair_candidate">建议回补 {{ gapCount('repair_candidate') }}</el-radio-button><el-radio-button label="needs_review">待核验 {{ gapCount('needs_review') }}</el-radio-button><el-radio-button label="known_no_data">已知无数据 {{ gapCount('known_no_data') }}</el-radio-button></el-radio-group><el-button :disabled="!selectedVerifyItems.length" :loading="verifying" @click="createVerify">Baostock 核验（{{ selectedVerifyItems.length }}）</el-button><el-button type="primary" :disabled="!selectedRepairItems.length" :loading="repairing" @click="createRepair">创建定向回补（{{ selectedRepairItems.length }}）</el-button></div></div>
      <el-table :data="filteredGapDetails" height="560" empty-text="当前筛选条件下没有缺口" @selection-change="selectedItems = $event"><el-table-column type="selection" width="48" :selectable="isActionable" /><el-table-column prop="symbol" label="代码" width="110" /><el-table-column label="判断" width="115"><template #default="{ row }"><el-tag :type="classificationType(row.classification)" effect="plain">{{ classificationLabel(row.classification) }}</el-tag></template></el-table-column><el-table-column prop="recommendation" label="处理建议" width="105" /><el-table-column label="缺失交易日" min-width="210"><template #default="{ row }">{{ row.missing_dates.join(', ') }}</template></el-table-column><el-table-column prop="evidence" label="判定依据" min-width="230" show-overflow-tooltip /><el-table-column label="操作" width="125"><template #default="{ row }"><el-button v-if="row.classification === 'needs_review'" link type="warning" @click="reviewNoRepair(row)">确认无需回补</el-button></template></el-table-column></el-table>
    </section>
    <section class="window-overview"><div><strong>观察窗口概览</strong><span>最近 {{ lookbackDays }} 日，用于判断整体数据时效，不参与当前交易日的操作判断。</span><small v-if="snapshot?.summary.status === 'degraded'">完整度低于 99.50% 健康目标，请处理缺失标的。</small></div><dl><div><dt>最新交易日</dt><dd>{{ snapshot?.summary.latest_trade_date ?? '-' }}</dd></div><div><dt>最新物理覆盖</dt><dd>{{ formatNumber(snapshot?.summary.actual_symbols) }} / {{ formatNumber(snapshot?.summary.expected_symbols) }}</dd></div><div><dt>数据状态</dt><dd><el-tag :type="healthType(snapshot?.summary.status)">{{ mootdxStatusText(snapshot?.summary.status ?? 'loading') }}</el-tag></dd></div></dl></section>
  </section>
</template>
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useRouter } from 'vue-router'
import { api, type JobRecord, type MootdxDailyQualityResponse } from '../api/client'
import { mootdxStatusText } from '../features/mootdx/formatters'
const router = useRouter(); const snapshot = ref<MootdxDailyQualityResponse | null>(null); const activeJob = ref<JobRecord | null>(null); const loading = ref(false); const repairing = ref(false); const verifying = ref(false); const lookbackDays = ref(30); const gapFilter = ref('all'); const selectedTradeDate = ref(''); const selectedItems = ref<MootdxDailyQualityResponse['missing_details']>([]); let pollTimer: ReturnType<typeof setTimeout> | null = null
const dailyCoverageOptions = computed(() => [...(snapshot.value?.daily_coverage ?? [])].reverse()); const selectedCoverage = computed(() => dailyCoverageOptions.value.find(item => item.trade_date === selectedTradeDate.value)); const dateGapDetails = computed(() => (snapshot.value?.missing_details ?? []).map(item => ({ ...item, missing_dates: item.missing_dates.filter(value => value === selectedTradeDate.value) })).filter(item => item.missing_dates.includes(selectedTradeDate.value))); function gapCount(value: string) { return dateGapDetails.value.filter(item => item.classification === value).length }; const resolvedNoDataCount = computed(() => gapCount('known_no_data') + gapCount('reviewed_no_repair')); const actionableGapCount = computed(() => gapCount('repair_candidate') + gapCount('needs_review')); const effectiveCoverageRate = computed(() => { const expected = selectedCoverage.value?.expected_symbols ?? 0; const actual = selectedCoverage.value?.actual_symbols ?? 0; return expected ? Math.min(1, (actual + resolvedNoDataCount.value) / expected) : 0 }); function formatNumber(value?: number) { return new Intl.NumberFormat('zh-CN').format(value ?? 0) }; function percentage(value?: number) { return `${((value ?? 0) * 100).toFixed(2)}%` }; function healthType(value?: string) { return value === 'healthy' ? 'success' : value === 'failed' || value === 'unavailable' ? 'danger' : 'warning' }; function classificationLabel(value: string) { return ({ repair_candidate: '建议回补', needs_review: '待核验', known_no_data: '已知无数据', reviewed_no_repair: '人工确认无需回补' } as Record<string, string>)[value] ?? value }; function classificationType(value: string) { return value === 'repair_candidate' ? 'danger' : value === 'needs_review' ? 'warning' : 'info' }; function isActionable(row: MootdxDailyQualityResponse['missing_details'][number]) { return row.classification === 'repair_candidate' || row.classification === 'needs_review' }; function jobLabel(kind: string) { return kind === 'mootdx_daily_gap_verify' ? 'Baostock 核验任务' : '定向回补任务' }
const selectedRepairItems = computed(() => selectedItems.value.filter(item => item.classification === 'repair_candidate')); const selectedVerifyItems = computed(() => selectedItems.value.filter(item => item.classification === 'needs_review')); const filteredGapDetails = computed(() => dateGapDetails.value.filter(item => gapFilter.value === 'all' || item.classification === gapFilter.value)); const payload = (items: MootdxDailyQualityResponse['missing_details']) => items.map(item => ({ symbol: item.symbol, start_date: selectedTradeDate.value, end_date: selectedTradeDate.value, evidence: item.evidence }))
function selectTradeDate(tradeDate: string) { selectedTradeDate.value = tradeDate; selectedItems.value = [] }
async function load() { loading.value = true; try { snapshot.value = await api.getMootdxDailyQuality(lookbackDays.value, 1000); const latest = snapshot.value.summary.latest_trade_date ?? ''; selectedTradeDate.value = dailyCoverageOptions.value.some(item => item.trade_date === selectedTradeDate.value) ? selectedTradeDate.value : latest; selectedItems.value = [] } catch (error) { ElMessage.error(error instanceof Error ? error.message : '加载日线质量失败') } finally { loading.value = false } }
async function pollJob() { if (!activeJob.value) return; activeJob.value = await api.getJob(activeJob.value.id); if (activeJob.value.status === 'pending' || activeJob.value.status === 'running') { pollTimer = setTimeout(pollJob, 2000) } else { await load() } }
async function trackJob(jobId: string) { if (pollTimer) clearTimeout(pollTimer); activeJob.value = await api.getJob(jobId); await pollJob() }
async function createRepair() { repairing.value = true; try { const result = await api.createMootdxDailyGapRepair(payload(selectedRepairItems.value)); ElMessage.success('已创建定向回补任务'); await trackJob(result.job_id) } catch (error) { ElMessage.error(error instanceof Error ? error.message : '创建定向回补失败') } finally { repairing.value = false } }
async function createVerify() { verifying.value = true; try { const result = await api.createMootdxDailyGapVerify(payload(selectedVerifyItems.value)); ElMessage.success('已创建 Baostock 核验任务'); await trackJob(result.job_id) } catch (error) { ElMessage.error(error instanceof Error ? error.message : '创建核验任务失败') } finally { verifying.value = false } }
async function reviewNoRepair(item: MootdxDailyQualityResponse['missing_details'][number]) { try { const { value } = await ElMessageBox.prompt('请填写核验结论，例如：已确认停牌、退市/摘牌、源端无历史。', '确认无需回补', { inputPattern: /\S{2,}/, inputErrorMessage: '核验原因至少填写两个字符' }); await api.reviewMootdxDailyGapNoRepair({ symbol: item.symbol, start_date: item.missing_dates[0], end_date: item.missing_dates.at(-1) ?? item.missing_dates[0], reason: value }); await load() } catch (error) { if (error !== 'cancel' && error !== 'close') ElMessage.error(error instanceof Error ? error.message : '提交核验结论失败') } }
onMounted(load); onBeforeUnmount(() => { if (pollTimer) clearTimeout(pollTimer) })
</script>
<style scoped>
.page-header,.toolbar,.section-header,.gap-actions,.job-panel,.date-query{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.page-header{margin-bottom:18px}.toolbar,.gap-actions,.date-query{align-items:center;flex-wrap:wrap;justify-content:flex-end}.page-title{margin:0}.page-subtitle,.section-header p,.job-panel span,.job-panel small,.date-query small,.queue-toolbar small,.coverage-day small,.selected-day-heading span,.window-overview span,.window-overview small{color:#667085;font-size:13px;line-height:1.45}.page-subtitle,.section-header p{margin:6px 0 0}.panel,.job-panel,.window-overview{border:1px solid #d9dee7;background:#fff;padding:14px}.section-header{margin-bottom:12px}.section-header h2{margin:0;font-size:17px}.coverage-strip{display:flex;gap:8px;overflow-x:auto;padding:0 0 14px;margin-bottom:12px;border-bottom:1px solid #eef1f5}.coverage-day{display:grid;flex:0 0 112px;gap:4px;padding:10px;border:1px solid #d9e2ef;border-radius:4px;background:#fff;color:#344054;text-align:left;cursor:pointer}.coverage-day:hover{border-color:#94b8f5}.coverage-day.active{border:2px solid #3b82f6;background:#f4f8ff;padding:9px}.coverage-day.complete strong{color:#237a4b}.coverage-day strong{font-size:15px;color:#bd4f35}.selected-day-summary{margin:0 0 16px;padding:14px;background:#f8fafc;border:1px solid #e4e9f1}.selected-day-heading{display:flex;align-items:baseline;gap:10px;margin-bottom:12px}.selected-day-heading strong{font-size:16px}.selected-day-metrics{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:12px}.selected-day-metrics>div{display:grid;gap:4px;min-width:0}.selected-day-metrics span{color:#667085;font-size:12px}.selected-day-metrics strong{font-size:20px;font-weight:650;color:#1d2939}.queue-toolbar{align-items:center}.queue-toolbar>div:first-child{display:grid;gap:4px}.job-panel{align-items:center;margin-bottom:18px}.job-panel>div:first-child{display:grid;gap:3px}.job-progress{min-width:260px;display:grid;gap:4px}.window-overview{display:flex;justify-content:space-between;gap:24px;align-items:center;margin-top:18px}.window-overview>div{display:grid;gap:4px}.window-overview dl{display:flex;gap:28px;margin:0}.window-overview dl>div{display:grid;gap:4px}.window-overview dt{font-size:12px;color:#667085}.window-overview dd{margin:0;color:#344054;font-weight:600}@media(max-width:980px){.selected-day-metrics{grid-template-columns:repeat(3,minmax(0,1fr))}.window-overview{align-items:flex-start;flex-direction:column}.window-overview dl{width:100%;justify-content:space-between}}@media(max-width:620px){.page-header,.job-panel,.section-header{flex-direction:column}.selected-day-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.job-progress{min-width:100%;width:100%}.window-overview dl{display:grid;grid-template-columns:1fr 1fr;gap:16px}}
</style>
